// Code generated by MockGen. DO NOT EDIT.
// Source: shortener.go
//
// Generated by this command:
//
//	mockgen -source=shortener.go -destination=mock_shortener.go -package=shortener
//

// Package shortener is a generated GoMock package.
package shortener

import (
	context "context"
	reflect "reflect"

	model "github.com/paulwwyvern/urlshortener/internal/model"
	dto "github.com/paulwwyvern/urlshortener/internal/model/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// GetShortURL mocks base method.
func (m *MockURLRepository) GetShortURL(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURL indicates an expected call of GetShortURL.
func (mr *MockURLRepositoryMockRecorder) GetShortURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURL", reflect.TypeOf((*MockURLRepository)(nil).GetShortURL), ctx, url)
}

// GetURL mocks base method.
func (m *MockURLRepository) GetURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockURLRepositoryMockRecorder) GetURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockURLRepository)(nil).GetURL), ctx, shortURL)
}

// GetUserURL mocks base method.
func (m *MockURLRepository) GetUserURL(ctx context.Context, userId int32) ([]dto.GetUserURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURL", ctx, userId)
	ret0, _ := ret[0].([]dto.GetUserURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURL indicates an expected call of GetUserURL.
func (mr *MockURLRepositoryMockRecorder) GetUserURL(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURL", reflect.TypeOf((*MockURLRepository)(nil).GetUserURL), ctx, userId)
}

// Ping mocks base method.
func (m *MockURLRepository) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockURLRepositoryMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockURLRepository)(nil).Ping), arg0)
}

// SaveURL mocks base method.
func (m *MockURLRepository) SaveURL(ctx context.Context, userId int32, shortURL, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, userId, shortURL, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockURLRepositoryMockRecorder) SaveURL(ctx, userId, shortURL, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockURLRepository)(nil).SaveURL), ctx, userId, shortURL, url)
}

// SaveURLBatch mocks base method.
func (m *MockURLRepository) SaveURLBatch(ctx context.Context, userId int32, urls []model.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURLBatch", ctx, userId, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURLBatch indicates an expected call of SaveURLBatch.
func (mr *MockURLRepositoryMockRecorder) SaveURLBatch(ctx, userId, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURLBatch", reflect.TypeOf((*MockURLRepository)(nil).SaveURLBatch), ctx, userId, urls)
}

// SoftDeleteURLBatch mocks base method.
func (m *MockURLRepository) SoftDeleteURLBatch(ctx context.Context, userId int32, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteURLBatch", ctx, userId, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteURLBatch indicates an expected call of SoftDeleteURLBatch.
func (mr *MockURLRepositoryMockRecorder) SoftDeleteURLBatch(ctx, userId, shortURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteURLBatch", reflect.TypeOf((*MockURLRepository)(nil).SoftDeleteURLBatch), ctx, userId, shortURLs)
}

// MockURLGenerator is a mock of URLGenerator interface.
type MockURLGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockURLGeneratorMockRecorder
	isgomock struct{}
}

// MockURLGeneratorMockRecorder is the mock recorder for MockURLGenerator.
type MockURLGeneratorMockRecorder struct {
	mock *MockURLGenerator
}

// NewMockURLGenerator creates a new mock instance.
func NewMockURLGenerator(ctrl *gomock.Controller) *MockURLGenerator {
	mock := &MockURLGenerator{ctrl: ctrl}
	mock.recorder = &MockURLGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLGenerator) EXPECT() *MockURLGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockURLGenerator) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockURLGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockURLGenerator)(nil).Generate))
}
