// Code generated by MockGen. DO NOT EDIT.
// Source: shortener.go
//
// Generated by this command:
//
//	mockgen -source=shortener.go -destination=mock_shortener.go -package=shortener
//

// Package shortener is a generated GoMock package.
package shortener

import (
	context "context"
	reflect "reflect"

	model "github.com/paulwwyvern/urlshortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUrlRepository is a mock of UrlRepository interface.
type MockUrlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRepositoryMockRecorder
	isgomock struct{}
}

// MockUrlRepositoryMockRecorder is the mock recorder for MockUrlRepository.
type MockUrlRepositoryMockRecorder struct {
	mock *MockUrlRepository
}

// NewMockUrlRepository creates a new mock instance.
func NewMockUrlRepository(ctrl *gomock.Controller) *MockUrlRepository {
	mock := &MockUrlRepository{ctrl: ctrl}
	mock.recorder = &MockUrlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRepository) EXPECT() *MockUrlRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockUrlRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockUrlRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockUrlRepository)(nil).Close))
}

// GetShortURL mocks base method.
func (m *MockUrlRepository) GetShortURL(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortURL indicates an expected call of GetShortURL.
func (mr *MockUrlRepositoryMockRecorder) GetShortURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortURL", reflect.TypeOf((*MockUrlRepository)(nil).GetShortURL), ctx, url)
}

// GetURL mocks base method.
func (m *MockUrlRepository) GetURL(ctx context.Context, shortUrl string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortUrl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockUrlRepositoryMockRecorder) GetURL(ctx, shortUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockUrlRepository)(nil).GetURL), ctx, shortUrl)
}

// GetUserURL mocks base method.
func (m *MockUrlRepository) GetUserURL(ctx context.Context, userId int32) ([]model.GetUserURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURL", ctx, userId)
	ret0, _ := ret[0].([]model.GetUserURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURL indicates an expected call of GetUserURL.
func (mr *MockUrlRepositoryMockRecorder) GetUserURL(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURL", reflect.TypeOf((*MockUrlRepository)(nil).GetUserURL), ctx, userId)
}

// Ping mocks base method.
func (m *MockUrlRepository) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockUrlRepositoryMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockUrlRepository)(nil).Ping), arg0)
}

// SaveURL mocks base method.
func (m *MockUrlRepository) SaveURL(ctx context.Context, userId int32, shortUrl, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, userId, shortUrl, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockUrlRepositoryMockRecorder) SaveURL(ctx, userId, shortUrl, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockUrlRepository)(nil).SaveURL), ctx, userId, shortUrl, url)
}

// SaveURLBatch mocks base method.
func (m *MockUrlRepository) SaveURLBatch(ctx context.Context, userId int32, urls []model.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURLBatch", ctx, userId, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURLBatch indicates an expected call of SaveURLBatch.
func (mr *MockUrlRepositoryMockRecorder) SaveURLBatch(ctx, userId, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURLBatch", reflect.TypeOf((*MockUrlRepository)(nil).SaveURLBatch), ctx, userId, urls)
}

// MockUrlGenerator is a mock of UrlGenerator interface.
type MockUrlGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUrlGeneratorMockRecorder
	isgomock struct{}
}

// MockUrlGeneratorMockRecorder is the mock recorder for MockUrlGenerator.
type MockUrlGeneratorMockRecorder struct {
	mock *MockUrlGenerator
}

// NewMockUrlGenerator creates a new mock instance.
func NewMockUrlGenerator(ctrl *gomock.Controller) *MockUrlGenerator {
	mock := &MockUrlGenerator{ctrl: ctrl}
	mock.recorder = &MockUrlGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlGenerator) EXPECT() *MockUrlGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUrlGenerator) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockUrlGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUrlGenerator)(nil).Generate))
}
