// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_handler.go -package=chihttp
//

// Package chihttp is a generated GoMock package.
package chihttp

import (
	context "context"
	reflect "reflect"

	dto "github.com/paulwwyvern/urlshortener/internal/model/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockShortenerService is a mock of ShortenerService interface.
type MockShortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerServiceMockRecorder
	isgomock struct{}
}

// MockShortenerServiceMockRecorder is the mock recorder for MockShortenerService.
type MockShortenerServiceMockRecorder struct {
	mock *MockShortenerService
}

// NewMockShortenerService creates a new mock instance.
func NewMockShortenerService(ctrl *gomock.Controller) *MockShortenerService {
	mock := &MockShortenerService{ctrl: ctrl}
	mock.recorder = &MockShortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerService) EXPECT() *MockShortenerServiceMockRecorder {
	return m.recorder
}

// DeleteURLBatch mocks base method.
func (m *MockShortenerService) DeleteURLBatch(ctx context.Context, userID int32, shortURLs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteURLBatch", ctx, userID, shortURLs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteURLBatch indicates an expected call of DeleteURLBatch.
func (mr *MockShortenerServiceMockRecorder) DeleteURLBatch(ctx, userID, shortURLs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLBatch", reflect.TypeOf((*MockShortenerService)(nil).DeleteURLBatch), ctx, userID, shortURLs)
}

// GenerateURL mocks base method.
func (m *MockShortenerService) GenerateURL(ctx context.Context, userID int32, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateURL", ctx, userID, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateURL indicates an expected call of GenerateURL.
func (mr *MockShortenerServiceMockRecorder) GenerateURL(ctx, userID, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateURL", reflect.TypeOf((*MockShortenerService)(nil).GenerateURL), ctx, userID, url)
}

// GenerateURLBatch mocks base method.
func (m *MockShortenerService) GenerateURLBatch(ctx context.Context, userID int32, urls []dto.GenerateURLBatchRequest) ([]dto.GenerateURLBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateURLBatch", ctx, userID, urls)
	ret0, _ := ret[0].([]dto.GenerateURLBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateURLBatch indicates an expected call of GenerateURLBatch.
func (mr *MockShortenerServiceMockRecorder) GenerateURLBatch(ctx, userID, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateURLBatch", reflect.TypeOf((*MockShortenerService)(nil).GenerateURLBatch), ctx, userID, urls)
}

// GetStats mocks base method.
func (m *MockShortenerService) GetStats(ctx context.Context) (dto.GetStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(dto.GetStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockShortenerServiceMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockShortenerService)(nil).GetStats), ctx)
}

// GetURL mocks base method.
func (m *MockShortenerService) GetURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockShortenerServiceMockRecorder) GetURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockShortenerService)(nil).GetURL), ctx, shortURL)
}

// GetUserURLs mocks base method.
func (m *MockShortenerService) GetUserURLs(ctx context.Context, userID int32) ([]dto.GetUserURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].([]dto.GetUserURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockShortenerServiceMockRecorder) GetUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockShortenerService)(nil).GetUserURLs), ctx, userID)
}

// Ping mocks base method.
func (m *MockShortenerService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortenerServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortenerService)(nil).Ping), ctx)
}
