// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_handler.go -package=chihttp
//

// Package chihttp is a generated GoMock package.
package chihttp

import (
	context "context"
	reflect "reflect"

	model "github.com/paulwwyvern/urlshortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockShortenerService is a mock of ShortenerService interface.
type MockShortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerServiceMockRecorder
	isgomock struct{}
}

// MockShortenerServiceMockRecorder is the mock recorder for MockShortenerService.
type MockShortenerServiceMockRecorder struct {
	mock *MockShortenerService
}

// NewMockShortenerService creates a new mock instance.
func NewMockShortenerService(ctrl *gomock.Controller) *MockShortenerService {
	mock := &MockShortenerService{ctrl: ctrl}
	mock.recorder = &MockShortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerService) EXPECT() *MockShortenerServiceMockRecorder {
	return m.recorder
}

// GenerateURL mocks base method.
func (m *MockShortenerService) GenerateURL(ctx context.Context, userId int32, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateURL", ctx, userId, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateURL indicates an expected call of GenerateURL.
func (mr *MockShortenerServiceMockRecorder) GenerateURL(ctx, userId, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateURL", reflect.TypeOf((*MockShortenerService)(nil).GenerateURL), ctx, userId, url)
}

// GenerateURLBatch mocks base method.
func (m *MockShortenerService) GenerateURLBatch(ctx context.Context, userId int32, urls []model.GenerateURLBatchRequest) ([]model.GenerateURLBatchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateURLBatch", ctx, userId, urls)
	ret0, _ := ret[0].([]model.GenerateURLBatchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateURLBatch indicates an expected call of GenerateURLBatch.
func (mr *MockShortenerServiceMockRecorder) GenerateURLBatch(ctx, userId, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateURLBatch", reflect.TypeOf((*MockShortenerService)(nil).GenerateURLBatch), ctx, userId, urls)
}

// GetURL mocks base method.
func (m *MockShortenerService) GetURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockShortenerServiceMockRecorder) GetURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockShortenerService)(nil).GetURL), ctx, shortURL)
}

// GetUserURLs mocks base method.
func (m *MockShortenerService) GetUserURLs(ctx context.Context, userId int32) ([]model.GetUserURLResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userId)
	ret0, _ := ret[0].([]model.GetUserURLResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockShortenerServiceMockRecorder) GetUserURLs(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockShortenerService)(nil).GetUserURLs), ctx, userId)
}

// Ping mocks base method.
func (m *MockShortenerService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockShortenerServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockShortenerService)(nil).Ping), ctx)
}
