package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"text/template"
)

var basicZero = map[string]string{
	"bool":       "false",
	"string":     `""`,
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uintptr":    "0",
	"byte":       "0",
	"rune":       "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
}

const (
	typeFile int = iota
	typeVar
	typeSlice
	typeMap
	typeStruct
	typePointer
)

const templateFile = `// Code generated by reset; DO NOT EDIT.
// This file was generated by {{.Exec}}
package {{.Name}}

{{range .Structs}}
func ({{.ShortName}} *{{.Name}}) Reset() {
	if {{.ShortName}} == nil {
		return
	}{{range .NullifyFields}} 
	{{ . }}{{end}}
}
{{end}}

`

const templateVar = `{{.name}} = {{.zero}}`

const templateSlice = `{{.name}} = {{.name}}[:0]`

const templateMap = `clear({{.name}})`

const templateStruct = `if resetter, ok := interface{}({{.name}}).(interface{ Reset() }); ok {
	resetter.Reset()
}`

const templatePointer = `if {{.name}} != nil {
{{ .body }}
}`

type Generator struct {
	templates map[int]*template.Template
}

func NewGenerator() *Generator {
	templates := map[int]*template.Template{
		typeFile:    template.Must(template.New("").Parse(templateFile)),
		typeVar:     template.Must(template.New("").Parse(templateVar)),
		typeSlice:   template.Must(template.New("").Parse(templateSlice)),
		typeMap:     template.Must(template.New("").Parse(templateMap)),
		typeStruct:  template.Must(template.New("").Parse(templateStruct)),
		typePointer: template.Must(template.New("").Parse(templatePointer)),
	}

	return &Generator{templates: templates}
}

// GenerateFile выдаёт сгенеренную фактически готовый файл
func (g *Generator) GenerateFile(p *PackageData) []byte {
	var buf bytes.Buffer
	g.templates[typeFile].Execute(&buf, p)

	formatted, _ := format.Source(buf.Bytes())

	return formatted
}

// GenerateNullifyField генерит то как будет обнулятся name в зависимости от того, что за тип спрятан под e
func (g *Generator) GenerateNullifyField(structName string, name string, e ast.Expr) string {
	return g.generateNullifyField(structName+"."+name, e)
}

func (g *Generator) generateNullifyField(name string, e ast.Expr) string {
	var buf bytes.Buffer
	var t *template.Template
	data := map[string]string{
		"name": name,
	}

	switch e := e.(type) {
	case *ast.Ident:
		// тут могут попасться либо обычные переменные, либо структуры из того же пакета
		zeroVal, ok := basicZero[e.Name]
		if ok {
			data["zero"] = zeroVal

			t = g.templates[typeVar]
		} else {
			t = g.templates[typeStruct]
		}
	case *ast.SelectorExpr:
		// тут попадаются структуры из другого пакета
		t = g.templates[typeStruct]
	case *ast.StarExpr:
		// тут ссылки
		body := g.generateNullifyField("*"+name, e.X)
		data["body"] = body

		t = g.templates[typePointer]
	case *ast.SliceExpr:
		// тут слайсы
		t = g.templates[typeSlice]
	case *ast.ArrayType:
		// тут массив
		t = g.templates[typeSlice]
	case *ast.MapType:
		// тут мапы
		t = g.templates[typeMap]
	default:
		// тут всё остальное что не было учтено
		t = g.templates[typeStruct]
	}

	err := t.Execute(&buf, data)
	if err != nil {
		panic(err)
	}
	return buf.String()
}
