// Code generated by MockGen. DO NOT EDIT.
// Source: workers.go
//
// Generated by this command:
//
//	mockgen -source=workers.go -destination=mock_workers.go -package=workers
//

// Package workers is a generated GoMock package.
package workers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPurgeURLRepository is a mock of PurgeURLRepository interface.
type MockPurgeURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurgeURLRepositoryMockRecorder
	isgomock struct{}
}

// MockPurgeURLRepositoryMockRecorder is the mock recorder for MockPurgeURLRepository.
type MockPurgeURLRepositoryMockRecorder struct {
	mock *MockPurgeURLRepository
}

// NewMockPurgeURLRepository creates a new mock instance.
func NewMockPurgeURLRepository(ctrl *gomock.Controller) *MockPurgeURLRepository {
	mock := &MockPurgeURLRepository{ctrl: ctrl}
	mock.recorder = &MockPurgeURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurgeURLRepository) EXPECT() *MockPurgeURLRepositoryMockRecorder {
	return m.recorder
}

// PurgeURLBatch mocks base method.
func (m *MockPurgeURLRepository) PurgeURLBatch(ctx context.Context, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgeURLBatch", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeURLBatch indicates an expected call of PurgeURLBatch.
func (mr *MockPurgeURLRepositoryMockRecorder) PurgeURLBatch(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeURLBatch", reflect.TypeOf((*MockPurgeURLRepository)(nil).PurgeURLBatch), ctx, urls)
}
