// Code generated by MockGen. DO NOT EDIT.
// Source: shortener.go
//
// Generated by this command:
//
//	mockgen -source=shortener.go -destination=mock_shortener.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUrlRepository is a mock of UrlRepository interface.
type MockUrlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRepositoryMockRecorder
	isgomock struct{}
}

// MockUrlRepositoryMockRecorder is the mock recorder for MockUrlRepository.
type MockUrlRepositoryMockRecorder struct {
	mock *MockUrlRepository
}

// NewMockUrlRepository creates a new mock instance.
func NewMockUrlRepository(ctrl *gomock.Controller) *MockUrlRepository {
	mock := &MockUrlRepository{ctrl: ctrl}
	mock.recorder = &MockUrlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRepository) EXPECT() *MockUrlRepositoryMockRecorder {
	return m.recorder
}

// GetURL mocks base method.
func (m *MockUrlRepository) GetURL(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockUrlRepositoryMockRecorder) GetURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockUrlRepository)(nil).GetURL), arg0, arg1)
}

// SaveURL mocks base method.
func (m *MockUrlRepository) SaveURL(ctx context.Context, shortUrl, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveURL", ctx, shortUrl, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveURL indicates an expected call of SaveURL.
func (mr *MockUrlRepositoryMockRecorder) SaveURL(ctx, shortUrl, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveURL", reflect.TypeOf((*MockUrlRepository)(nil).SaveURL), ctx, shortUrl, url)
}

// MockUrlGenerator is a mock of UrlGenerator interface.
type MockUrlGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockUrlGeneratorMockRecorder
	isgomock struct{}
}

// MockUrlGeneratorMockRecorder is the mock recorder for MockUrlGenerator.
type MockUrlGeneratorMockRecorder struct {
	mock *MockUrlGenerator
}

// NewMockUrlGenerator creates a new mock instance.
func NewMockUrlGenerator(ctrl *gomock.Controller) *MockUrlGenerator {
	mock := &MockUrlGenerator{ctrl: ctrl}
	mock.recorder = &MockUrlGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlGenerator) EXPECT() *MockUrlGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockUrlGenerator) Generate() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockUrlGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockUrlGenerator)(nil).Generate))
}
