// Code generated by reset; DO NOT EDIT.
// This file was generated by /home/paul/Documents/yandex/urlshortener/cmd/reset/reset
package main

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	r.a = [10]int{}
	if r.m != nil {
		clear(*r.m)
	}
	if r.r != nil {
		if *r.r != nil {
			if **r.r != nil {
				if resetter, ok := interface{}(**r.r).(interface{ Reset() }); ok {
					resetter.Reset()
				}
			}
		}
	}
}
