// Code generated by reset; DO NOT EDIT.
// This file was generated by ./cmd/reset/reset
package main

func (r *ResetableStruct) Reset() {
	if r == nil {
		return
	}
	r.i = 0
	r.str = ""
	if r.strP != nil {
		*r.strP = ""
	}
	r.s = r.s[:0]
	clear(r.m)
	if resetter, ok := interface{}(r.r).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
